version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: laravel_app
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - laravel
    depends_on:
      - db

  server:
    image: nginx:latest
    container_name: server
    ports:
      - "80:80"
      - "3000:3000"  # Port for Vite's development server
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - node  # Make sure nginx waits for the node container
    networks:
      - laravel

  db:
    image: mysql:5.7
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel

  composer:
    image: composer:latest
    container_name: laravel_composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    command: composer install
    networks:
      - laravel

  node:
    image: node:18-alpine
    container_name: laravel_node
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    command: sh -c "npm install && npm run dev"
    networks:
      - laravel
    ports:
      - "5173:5173"  # Port for Vite's HMR (Hot Module Replacement)

networks:
  laravel:
    driver: bridge

volumes:
  db_data:
